### PR TITLE
docs: update copyright header of source file

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>

### Ⅰ. Describe what this PR did

update copyright header of source file from `Copyright 1999-2018 Alibaba Group.` to `Copyright The Dragonfly Authors.`

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/dragonflyoss/Dragonfly/issues/248

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
no need

### Ⅳ. Describe how to verify it
none

### Ⅴ. Special notes for reviews
none

### CODE REVIEW

**Comment by lowzj** [comment]
The bad link problem is caused by the change of domain `d7y.io`, I will fix it later.

**Comment by zhouhaibing089** [comment]
Also a heads up here, do we want to enforce header presence for every source files?

**Comment by allencloud** [comment]
> Also a heads up here, do we want to enforce header presence for every source files?

You mean not only the Go source file, but also any other files? @zhouhaibing089

**Comment by zhouhaibing089** [comment]
@allencloud: And also a check in CI jobs(if we haven't done so already)..

**Pull request merged**
