### PR TITLE
cleanup: server.go flag help massage typo fix

### PR DESCRIPTION
**Pull request by ethan-daocloud**
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

### Ⅰ. Describe what this PR did
fix typo in flag message

### Ⅱ. Does this pull request fix one issue?
maybe not

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
no need test ;)

### CODE REVIEW

**Comment by yeya24** [comment]
Thanks for your contribution.
I find that there are some same typos here. https://github.com/dragonflyoss/Dragonfly/search?q=automically&unscoped_q=automically 
Can you address them all in this PR? @ethan-daocloud

**Comment by Starnop** [comment]
LGTM.

**Comment by ethan-daocloud** [comment]
@yeya24 
sure, I want to and can do this in this pr, before it's too late
@Starnop 
No disrespect, thanks for your quick action.

**Comment by yeya24** [comment]
@ethan-daocloud  It is OK and you can still open a new PR to address these typos.

**Pull request merged**
