### PR TITLE
refactor: unify the same field type definition in different places

### PR DESCRIPTION
**Pull request by fengzixu**
Signed-off-by: fengzixu <hnustphoenix@gmail.com>

### Ⅰ. Describe what this PR did

1. reduce using of extra fields which were included in anthor definition

### Ⅱ. Does this pull request fix one issue?

#363 

### Ⅳ. Describe how to verify it

I run all unit-test in the dfget package.

### Ⅴ. Special notes for reviews

For 「use int32 or int64 instead of int」, I think that using 'int' is ok for the dfget package. We don't need to revise all variables whose type is int into a wider type.

For 「unify the same field type definition in different places」, I revise the code which was written in the package called downloader. Because I consider that we should not add extra variables that are already defined elsewhere.

### CODE REVIEW

**Comment by fengzixu** [comment]
@Starnop Request review.

**Comment by Starnop** [comment]
Thanks for your contribution. However, maybe it's not a good solution. And in fact, I am trying to fix the issue #370 which is just the opposite of what you did. 😢 

And for issue issue #363, I think what should we do is just as title described. For example, we think that `int32` is enough for `pieceSize`. However, it's defined with `int64` [here](https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/core/uploader/peer_server.go#L104). And that is exactly what we should make a change. 

And the other similar fields but not completely, just FYI:
+ pieceNum (expected int64)
+ port (int32/int both OK but should be unified)
+ ......

**Comment by fengzixu** [comment]
> * unified

Ok. Let me fix the problem about integer type. I will give up the modification of configuration type.

**Comment by Starnop** [comment]
Any updates?

**Comment by fengzixu** [comment]
@Starnop Sorry. I am too busy at the current time. I will finish it asap.

**Comment by Starnop** [comment]
Don't worry about that. I just want to get the latest progress.  Whatever, thanks for your work. 😄

**Pull request closed without merging**
