### PR TITLE
update supernode metrics

### PR DESCRIPTION
**Pull request by jim3ma**
### Ⅰ. Describe what this PR did

1. add metrics `dragonfly_supernode_cdn_download_size_bytes_total` for #1458
2. update statistical accuracy for some durations
3. update grafana dashboard config.

### Ⅱ. Does this pull request fix one issue?

#1458 

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

N/A

### Ⅳ. Describe how to verify it

N/A

### CODE REVIEW

**Comment by Starnop** [comment]
image

@jim3ma Please try to pass the CI system firstly.

**Comment by yeya24** [comment]
I re-run the CI. Seems it is not related to this pr.

**Review by yeya24 — APPROVED** [review]
The new metric looks good!

**Comment by Starnop** [comment]
@jim3ma Should we update the file `https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/dragonfly.json` synchronously?

**Comment by jim3ma** [comment]
> @jim3ma Should we update the file `https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/dragonfly.json` synchronously?

Yes, I will update this later.

**Comment by jim3ma** [comment]
@Starnop back source size dashboard:
Screen Shot 2020-09-24 at 10 12 52 PM

**Pull request merged**
