### PR TITLE
docs: remove wangj998 and add Starnop in MAINTAINER.md

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>

### Ⅰ. Describe what this PR did

@wangj998 is a great guy for project Dragonfly. When Dragonfly is not a CNCF project, he contributed a lot to spread the technology to the whole industry in Alibaba. Without him, Dragonfly cannot be a wide-spread software project at all. While currently he is not able to maintain Dragonfly any more, and he is doing great work in other field. We are going to remove @wangj998 from the maintainers list, while in the following days we still wish @wangj998 to care this project.

@Starnop is now making quite many efforts in bring success to project Dragonfly. He is very active contributor in maintaining the original Java-based supernode, and now mainly focuses on refactoring the Golang version of the whole project. In addition, he starts up the Helm-Chart of Dragonfly to support it in Kubernetes. He is from Zhejiang University and now works in Alibaba. 
Dragonfly community always welcomes all kinds of contributing. With the trust @Starnop built in the community, I proposed to add @Starnop as a maintainer in Dragonfly project.

Please help to review this, and feel free to comment on it if anyone in the community has issues.

### Ⅱ. Does this pull request fix one issue?

none

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
no need. just doc-related.

### Ⅳ. Describe how to verify it
none

### Ⅴ. Special notes for reviews

cc @lowzj @zhouhaibing089 @garfield009 @chenchaobing

### CODE REVIEW

**Comment by fengzixu** [comment]
Congratulations @Starnop.

**Comment by garfield009** [comment]
lgtm

**Comment by allencloud** [comment]
LGTM

**Comment by zhouhaibing089** [comment]
LGTM

**Comment by allencloud** [comment]
Thanks for all your kind confirmation. Merging...
And congratulations, @Starnop

**Pull request merged**
