### PR TITLE
bugfix:Improve the readability of code

### PR DESCRIPTION
**Pull request by Aresforchina**
### Ⅰ. Describe what this PR did
Increase the quality of articles and correct spelling mistakes

### Ⅱ. Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by yeya24** [comment]
@Aresforchina  From the CI, it produced the error below. You need to change supernode_errors.go as well
```
../../pkg/errortypes/supernode_errors.go:72:25: undefined: codeUnknowError
```

**Comment by Aresforchina** [comment]
> @Aresforchina From the CI, it produced the error below. You need to change supernode_errors.go as well
> 
> ```
> ../../pkg/errortypes/supernode_errors.go:72:25: undefined: codeUnknowError
> ```

@yeya24 yaa!I have already fix it.

**Comment by yunfeiyanggzq** [comment]
LGTM

**Comment by allencloud** [comment]
LGTM

**Pull request merged**
