### PR TITLE
docs: fix wrong command.

### LINKED ISSUE #875: When make install the dragonfly, the log show:cannot stat ‘../bin/linux_amd64/dfdaemon’: No such file or directory
## Question

make build-supernode && make install
......
Begin to install dfget and dfdaemon and supernode.
./hack/install.sh install
install: /opt/dragonfly/df-client
cp: cannot stat ‘../bin/linux_amd64/dfdaemon’: No such file or directory
make: *** [install] Error 1

### PR DESCRIPTION
**Pull request by hwdef**
### Ⅰ. Describe what this PR did

fix bug in docs

### Ⅱ. Does this pull request fix one issue?

fixes #875

### CODE REVIEW

**Comment by hwdef** [comment]
@Starnop

**Comment by hwdef** [comment]
@lowzj 
Thanks for your suggestion.
I changed it.
Is it the correct format?

**Comment by lowzj** [comment]
I mean to format the commit message, refer to [commit message](https://github.com/dragonflyoss/Dragonfly/blob/master/CONTRIBUTING.md#commit-message).

You can use the following command to amend your previous commit:
```
git commit --amend
```

**Comment by hwdef** [comment]
@lowzj 
Sorry, I misunderstood what you mean.
I changed it,please check.

**Pull request merged**
