### PR TITLE
docs: reorganize documents structure of Dragonfly

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: Allen Sun <allensun.shl@alibaba-inc.com>

### Ⅰ. Describe what this PR did

This PR  reorganizes documents structure of Dragonfly.

Since we have already used repo https://github.com/dragonflyoss/website as the source details of https://d7y.io. So we do not have to contains so many unrelated docs in this repo.

So I did:

1. find a new structure of docs organization:

* Quick Start
* User Guide
* CLI Reference
    * dfget
    * dfdaemon
    * supernode
* API Reference
* Ecosystem
    * Kubernetes Integration
    * Harbor Integration
* Developer Guide
    * Design Doc
    * Test Guide

2. remove other useless document.

### Ⅱ. Does this pull request fix one issue?

none

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
no need

### Ⅳ. Describe how to verify it
none

### Ⅴ. Special notes for reviews
none

### CODE REVIEW

**Comment by Starnop** [comment]
+ Please rebase the master branch and the `design doc` should not be an empty file.
+ What about the directory of [overview](https://github.com/dragonflyoss/Dragonfly/tree/master/docs/overview) ?
+ Re-run CI to pass the test that may fail due to network problems.

**Comment by Starnop** [comment]
> For the overview part, it will be moved into website repo. Since it is specific for website.

If so, why don't you delete the dir of [overview](https://github.com/dragonflyoss/Dragonfly/tree/master/docs/overview)?

**Comment by allencloud** [comment]
> If so, why don't you delete the dir of overview?

Ah, my bad. Removed now.

**Comment by Starnop** [comment]
LGTM.

**Pull request merged**
