### PR TITLE
docs:optimize the quick-start doc

### PR DESCRIPTION
**Pull request by yunfeiyangbuaa**
### Ⅰ. Describe what this PR did
docker container uses utc time and the host uses cst time,so the log's time is different from the host.so maybe it is better to make time synchronization when we start a container

### CODE REVIEW

**Comment by lowzj** [comment]
IMOP, it's unnecessary for us to add this in quick-start document.

**Comment by allencloud** [comment]
Any feedback for @lowzj 's thought? @yunfeiyangbuaa

**Comment by yunfeiyangbuaa** [comment]
> Any feedback for @lowzj 's thought? @yunfeiyangbuaa
it only a optimize for user to understand  the log,but it will make the quick start more  confused  to newer ,so  it may be better if we abandon this optimize

**Comment by Starnop** [comment]
> it only a optimize for user to understand the log,but it will make the quick start more confused to newer ,so it may be better if we abandon this optimize


@yunfeiyangbuaa Maybe you can add it as an item of FAQ. WDYT?

**Comment by yunfeiyangbuaa** [comment]
> > it only a optimize for user to understand the log,but it will make the quick start more confused to newer ,so it may be better if we abandon this optimize
> 
> @yunfeiyangbuaa Maybe you can add it as an item of FAQ. WDYT?

I will work on it. @Starnop

**Comment by Starnop** [comment]
Any updates?

**Pull request closed without merging**
