### PR TITLE
bugfix:modify the words spelling mistakes

### PR DESCRIPTION
**Pull request by Aresforchina**
### Ⅰ. Describe what this PR did
Increase the quality of articles and correct spelling mistakes

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
do not need

### CODE REVIEW

**Comment by allencloud** [comment]
I found lots of such issue in this repo: https://github.com/dragonflyoss/Dragonfly/search?q=unknow&unscoped_q=unknow
Could you help to fix them all? @Aresforchina Thanks

**Comment by Aresforchina** [comment]
@allencloud Of course, I'll fix them

**Comment by yunfeiyanggzq** [comment]
> @allencloud Of course, I'll fix them

any progress? if you want to fix them in other prs,I can merge this pr

**Comment by Aresforchina** [comment]
@yunfeiyanggzq Firstly i will say thanks for you.In fact,i had already fix them about "unknow" in https://github.com/dragonflyoss/Dragonfly/pull/1134 .but the bot told me the compile did not pass.
Could you give me some advices?

**Comment by Starnop** [comment]
LGTM.

**Pull request merged**
