### PR TITLE
docs:add FAQ.md abot how dfget connect to supernodes in mul-supernode mode

### PR DESCRIPTION
**Pull request by yunfeiyanggzq**
Signed-off-by: yunfeiyangbuaa <yunfeiyang@buaa.edu.cn>

### Ⅰ. Describe what this PR did
too many questions about this in dingding group

### CODE REVIEW

**Comment by Starnop** [comment]
> too many questions about this in dingding group

Good job. Could you please sort out a list of questions and open an issue to record that? THX.

**Comment by yunfeiyanggzq** [comment]
> > too many questions about this in dingding group
> 
> Good job. Could you please sort out a list of questions and open an issue to record that? THX.

ok

**Comment by yunfeiyanggzq** [comment]
@Starnop  please review it again

**Comment by Starnop** [comment]
Good job. LGTM.

**Comment by Starnop** [comment]
> > too many questions about this in dingding group
> 
> Good job. Could you please sort out a list of questions and open an issue to record that? THX.

@yunfeiyanggzq And please don't forget to open an issue to trace it. THX. 😄

**Pull request merged**
