### PR TITLE
cmd: add error handling

### PR DESCRIPTION
**Pull request by hwdef**
### Ⅰ. Describe what this PR did

add error handling in cmd/dfget

### Ⅱ. Does this pull request fix one issue?

NONE

### CODE REVIEW

**Comment by yeya24** [comment]
Why you open 3 PR? Can you finish your work in #925 ?

**Comment by yeya24** [comment]
Why do you open 3 PR? Could you please finish your work in #924 ?

**Comment by hwdef** [comment]
@yeya24 
because they are in different folder.
I don't know if they should handle together.

**Comment by yeya24** [comment]
> @yeya24
> because they are in different folder.
> I don't know if they should handle together.

This codes are in the same purpose so it is OK to put in one PR.

**Comment by hwdef** [comment]
@yeya24 
I will Make up for this mistake.

**Comment by hwdef** [comment]
@yeya24 
I merged them to #924 .
And I will close this PR and #927

**Pull request closed without merging**
