### PR TITLE
Add CormickKneey as maintainer

### PR DESCRIPTION
**Pull request by gaius-qi**
Add CormickKneey as maintainer and 

## Description
- Add [CormickKneey](https://github.com/CormickKneey) as maintainer.
- Add [Garen Wen](https://github.com/garenwen) as emeritus maintainer.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
+1

**Comment by CormickKneey** [comment]
Thanks for trust. Let's make it better!

**Comment by imeoer** [comment]
+1

**Comment by bergwolf** [comment]
+1

**Comment by fcgxz2003** [comment]
+1

**Comment by chlins** [comment]
+1

**Pull request merged**
