### PR TITLE
gc bug fix

### PR DESCRIPTION
**Pull request by liudechi7**
### Ⅰ. Describe what this PR did
节点下线时间初始化为0，对于这种情况gc异常
时间戳转换错误：int64(gcm.cfg.PeerGCDelay) 默认返回180000000000，但是这里对比使用的是毫秒
当下载时间过长（比如10g大文件），由于异常gc导致下载失败

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

测试用例不好覆盖

### Ⅳ. Describe how to verify it
1.测试下载dfget较大文件，持续时间超过2分钟

### CODE REVIEW

**Comment by yunfeiyangbuaa** [comment]
after a long time task fail,because after a gc sleep,gc will begin and because `peerState.ServiceDownTime == 0 ` so code won't go into continue and the gc will delete the dfgetTask,so download fail

**Comment by liudechi7** [comment]
> after a long time task fail,because after a gc sleep(3min default),peer gc will begin and because `peerState.ServiceDownTime == 0 ` so code won't go into
> 
> ```
> 	if peerState.ServiceDownTime != 0 &&
> 			timeutils.GetCurrentTimeMillis()-peerState.ServiceDownTime < int64(gcm.cfg.PeerGCDelay) {
> 			continue
> 		}
> ```
> 
> and continue.
> 
> so the gc will delete the dfgetTask even if the dfgetTask haven't server down,so download fail.
> WDYT?

嗯就是这种情况导致的

**Comment by yunfeiyangbuaa** [comment]
@lowzj  the bug is fatal.please do with it as soon as possible https://github.com/dragonflyoss/Dragonfly/issues/844 and  https://github.com/dragonflyoss/Dragonfly/pull/851

**Comment by yunfeiyangbuaa** [comment]
sign: commit -s -m "xxxx"
you have two commits ,you should rebase your commits,
git  rebase -i  master

**Comment by liudechi7** [comment]
> sign: commit -s -m "xxxx"
> you have two commits ,you should rebase your commits,
> git rebase -i master

I create a new one,thx https://github.com/dragonflyoss/Dragonfly/pull/857

**Pull request closed without merging**
