### PR TITLE
docs: support private image which needs user/passwd for remote registries

### LINKED ISSUE #17: [question] How to support docker private registry.
I have a docker registry: docker.acmcoder.com. There are several public and private images in it.
I want to use dragonfly for image distribution.
After deploy, the public images can be pulled. but private images can not.

```
df-daemon:
df-daemon --registry https://docker.acmcoder.com -port 18001
```
```
dockerd
root@iZ2ze7tbgo9lk7jubiy6tcZ:~# cat /etc/docker/daemon.json
{
  "registry-mirrors": ["http://localhost:18001"]
}
```
```
root@iZ2ze7tbgo9lk7jubiy6tcZ:~# docker pull acmcoder/ubuntu:12days
Error response from daemon: repository acmcoder/ubuntu not found: does not exist or no pull access

root@iZ2ze7tbgo9lk7jubiy6tcZ:~# docker pull docker.acmcoder.com/acmcoder/ubuntu:12days
12days: Pulling from acmcoder/ubuntu
054be6183d06: Pull complete 
779578d7ea6e: Pull complete 
82315138c8bd: Pull complete 
88dc0000f5c4: Pull complete 
79f59e52a355: Pull complete 
a0b39032ccd2: Pull complete 
46c56af51e55: Pull complete 
1ee150f4e54b: Pull complete 
ead87fbf844e: Pull complete 
baa460bf3866: Pull complete 
0dd037bb5aaa: Pull complete 
Digest: sha256:3b1428d54bc875ff75eb8f0379516cbd04bb5e09b37024db4ac3bff574b88c7d
Status: Downloaded newer image for docker.acmcoder.com/acmcoder/ubuntu:12days
```

dockerd log:
ERRO[2258] Not continuing with pull after error: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
 
INFO[2258] Ignoring extra error returned from registry: unauthorized: authentication required 
INFO[2258] Translating "denied: requested access to the resource is denied" to "repository acmcoder/ubuntu not found: does not exist or no pull access" 
ERRO[2258] Handler for POST /v1.26/images/create returned error: repository acmcoder/ubuntu not found: does not exist or no pull access 

After I use docker login localhost:18001
It still can't work.

### PR DESCRIPTION
**Pull request by silenceshell**
Signed-off-by: silenceshell <me@ieevee.com>

### Ⅰ. Describe what this PR did

Add description about authentication for private docker registry.

### Ⅱ. Does this pull request fix one issue?

fixes #17 

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

No. just document.

### Ⅳ. Describe how to verify it

NA

### Ⅴ. Special notes for reviews

None

### CODE REVIEW

**Comment by allencloud** [comment]
do we need to restart the docker engine if the related auth configuration has been setup? @silenceshell

**Comment by silenceshell** [comment]
@allencloud 
No need. `docker` client will load `config.json` every time when executing.

**Comment by allencloud** [comment]
So this way is also suitable for any other third party registries? for example registry `mydomain.com/allencloud/imagename:testtag`? @silenceshell

**Comment by silenceshell** [comment]
For third party registry like `mydomain.com/allencloud/imagename:testtag`, we will pull the image without the prefix like `docker pull allencloud/imagename:testtag`.
Thus docker client will treat the image as a image from `docker.io` (whose auth API is `https://index.docker.io/v1/`), and  will try to find the authentication info in `~/.docker/config.json` for `docker.io`.
As we have setup the auth info for `docker.io`, docker client will get the auth info and call df-daemon proxy with auth header like `Autheorization:Bearer $token`. This header shows the access right(pull,push) for the repo and will help us to pass the authentication of the private registry.
However, I have only tested this against Harbor :sweat_smile:

**Comment by allencloud** [comment]
LGTM

**Comment by allencloud** [comment]
We need to update FAQ: https://github.com/dragonflyoss/Dragonfly/blob/master/FAQ.md#does-dragonfly-support-pulling-an-private-image-which-needs-usernamepassword-authentication.

**Pull request merged**
