### PR TITLE
docs: delete Yum China as a Dragonfly adopter

### PR DESCRIPTION
**Pull request by yaRammaG**
docs: delete Yum China as a Dragonfly adopter

### CODE REVIEW

**Comment by yeya24** [comment]
Could you please sign off your commit?

**Comment by yaRammaG** [comment]
delete Yum China as a Dragonfly adopter

**Comment by allencloud** [comment]
> delete Yum China as a Dragonfly adopter

talked with @yaRammaG that maybe it is not the best time to post YumChina here.

**Comment by allencloud** [comment]
LGTM if we solve the DCO issue.

**Pull request merged**
