### PR TITLE
Modify the Chinese punctuation mark to the English punctuation mark

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

### Ⅰ. Describe what this PR did
Modify the Chinese punctuation mark to the English punctuation mark.

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)
Don't need.

### CODE REVIEW

**Comment by Starnop** [comment]
Could you please help to check  if there are similar problems and fix them in this PR to avoid submitting PR for the same problem just like #876. THX.

**Comment by yuxiaobo96** [comment]
> @yuxiaobo96 Could you please help to check if there are similar problems and fix them in this PR to avoid submitting PR for the same problem just like #876. THX.

I'm sorry. I will take care of it later.

**Comment by Starnop** [comment]
> > @yuxiaobo96 Could you please help to check if there are similar problems and fix them in this PR to avoid submitting PR for the same problem just like #876. THX.
> 
> I'm sorry. I will take care of it later.

That's OK. And if you have completed the inspection of the entire project, please let me know. I will move on the process to merge this PR. 😄

**Comment by yuxiaobo96** [comment]
> > @yuxiaobo96 Could you please help to check if there are similar problems and fix them in this PR to avoid submitting PR for the same problem just like #876. THX.
> 
> I'm sorry. I will take care of it later.



> > > @yuxiaobo96 Could you please help to check if there are similar problems and fix them in this PR to avoid submitting PR for the same problem just like #876. THX.
> > 
> > 
> > I'm sorry. I will take care of it later.
> 
> That's OK. And if you have completed the inspection of the entire project, please let me know. I will move on the process to merge this PR.
>> Yes. I have checked the entire document. Please help me merge this PR. Thank you!

**Comment by Starnop** [comment]
LGTM.

**Pull request merged**
