### PR TITLE
doc: user guide to use dfdaemon as http proxy for docker

### PR DESCRIPTION
**Pull request by inoc603**
### Ⅰ. Describe what this PR did

**WIP**

Add a document to describe how to use dfdaemon as http proxy for docker. 

### Ⅱ. Does this pull request fix one issue?

Address one of the tasks in #596

### Ⅴ. Special notes for reviews

Really sorry for the delay. I've been very busy recently and didn't have much time to work on this. I'll try find time to finish it. Feel free to comment on the work in progress.

### CODE REVIEW

**Comment by Starnop** [comment]
@inoc603 Thanks for your work.  I think it's better to  provide a config template at the end of doc. WDYT?

**Comment by Starnop** [comment]
@inoc603 Could you please take some time to simply update the documentation which blocks the main process now? THX.

**Comment by inoc603** [comment]
Sure. I wrote a [simple guide to use proxy](https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/proxy.md) when it's implemented. I intend to move details about the proxy configuration there, and `docs/user_guide/docker_proxy.md` will focus on how to use proxy with docker, with a link at the end of it.

**Comment by Starnop** [comment]
LGTM. It will be better to add examples for `Download files` and  `Download images`. If you   have no space time to do that, and it's ok to assign it to me.

**Comment by inoc603** [comment]
> LGTM. It will be better to add examples for `Download files` and `Download images`. If you have no space time to do that, and it's ok to assign it to me.

I think we can add `download files` example in `proxy.md`, a `curl` example with both http/https would be enough. `download image` is pretty straight forward. I think a link to how to verify whether the image is been download with dfget will do.

**Pull request merged**
