### PR TITLE
typo: provice->provide

### PR DESCRIPTION
**Pull request by AdamDang**
typo: provice->provide

### Ⅰ. Describe what this PR did
Fix a typo in doc: provice->provide

### Ⅱ. Does this pull request fix one issue?

NONE

### Ⅲ. Why don't you add test cases (unit test/integration test)? (你真的觉得不需要加测试吗？)

no need

### Ⅳ. Describe how to verify it

typo.
### Ⅴ. Special notes for reviews

None

### CODE REVIEW

**Comment by yeya24** [comment]
Thanks for your contribution!
circleci failed unrelated, could you please sign off your DCO? :smile:
BTW I found there is a format problem in the link below , could you address it in this PR?
https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/multi_machines_deployment.md#prerequisites

**Comment by allencloud** [comment]
Any update? @AdamDang Thanks

**Comment by Starnop** [comment]
image

@AdamDang You can solve CI failure problem by clicking here.

**Comment by lowzj** [comment]
merged manually

**Pull request closed without merging**
